---
- hosts: myjenkins
  gather_facts: false
  vars:
    script_content: "{{ lookup('file', 'add-credentials.groovy')
      | regex_replace('System\\.getenv\\(\"(CREDENTIALS_ID)\"\\)', '\"${\\1}\"')
      | regex_replace('System\\.getenv\\(\"(CREDENTIALS_USER)\"\\)', '\"${\\1}\"')
      | regex_replace('System\\.getenv\\(\"(CREDENTIALS_PASS)\"\\)', '\"${\\1}\"') }}"
  vars_files:
    - vars.yml
  tasks:
    - name: Add new global credentials
      jenkins_script:
        script: "{{ script_content }}"
        args:
          CREDENTIALS_ID: "{{ item.id }}"
          CREDENTIALS_USER: "{{ item.username }}"
          CREDENTIALS_PASS: "{{ item.password }}"
        user: admin
        password: jenkins
      loop: "{{ global_credentials }}"
      no_log: True
      register: script_result
      changed_when: "'Result: true' in script_result.output"
