version: '3'
services:

  jenkins:
    build: .
    image: esignbr/myjenkins
    container_name: myjenkins
    environment:
      - SONARQUBE_URL=http://sonarqube:9000
    ports:
      - 8080:8080
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - 9000:9000
